requiredParams:
  name: FlowFragment by Alish
  description: Create FlowFragment

optionalParams:
  revision: 1
  category: fragment
  formFactor: mobile
  constraints:
    - kotlin
    - androidx
  screens:
    - fragment_gallery

widgets:
  - stringParameter:
      id: fragmentPrefix
      name: Fragment Prefix
      help: Prefix of the fragment and other classes to create
      constraints:
        - nonempty
        - unique
        - class
      default: Blank

globals:
  - stringParameter:
      id: flowFragmentName
      value: ${fragmentPrefix}FlowFragment

  - stringParameter:
      id: flowFragmentLayoutResName
      value: flow_fragment_${fragmentPrefix.camelCaseToUnderlines()}

  - stringParameter:
      id: graphName
      value: ${fragmentPrefix.camelCaseToUnderlines()}_graph

  - stringParameter:
      id: navHostFragmentName
      value: nav_host_fragment_${fragmentPrefix.camelCaseToUnderlines()}

recipe:
  - instantiateAndOpen:
      from: root/src/FlowFragment.kt.ftl
      to: ${srcOut}/${flowFragmentName}.kt

  - instantiateAndOpen:
      from: root/res/layout/flow_fragment.xml.ftl
      to: ${resOut}/layout/${flowFragmentLayoutResName}.xml

  - instantiateAndOpen:
      from: root/res/navigation/graph.xml.ftl
      to: ${resOut}/navigation/${graphName}.xml